package com.forestotzka.yurufu.sloves.block.enums;

import net.minecraft.util.StringIdentifiable;

public enum CustomVerticalSlabType implements StringIdentifiable {

    /* START MARKER */
    NONE("minecraft__air"),
    SLOVES__OAK_VERTICAL_SLAB("sloves__oak_vertical_slab"),
    SLOVES__SPRUCE_VERTICAL_SLAB("sloves__spruce_vertical_slab"),
    SLOVES__BIRCH_VERTICAL_SLAB("sloves__birch_vertical_slab"),
    SLOVES__JUNGLE_VERTICAL_SLAB("sloves__jungle_vertical_slab"),
    SLOVES__ACACIA_VERTICAL_SLAB("sloves__acacia_vertical_slab"),
    SLOVES__DARK_OAK_VERTICAL_SLAB("sloves__dark_oak_vertical_slab"),
    SLOVES__MANGROVE_VERTICAL_SLAB("sloves__mangrove_vertical_slab"),
    SLOVES__CHERRY_VERTICAL_SLAB("sloves__cherry_vertical_slab"),
    SLOVES__BAMBOO_VERTICAL_SLAB("sloves__bamboo_vertical_slab"),
    SLOVES__CRIMSON_VERTICAL_SLAB("sloves__crimson_vertical_slab"),
    SLOVES__WARPED_VERTICAL_SLAB("sloves__warped_vertical_slab"),
    SLOVES__BAMBOO_MOSAIC_VERTICAL_SLAB("sloves__bamboo_mosaic_vertical_slab"),
    SLOVES__STONE_VERTICAL_SLAB("sloves__stone_vertical_slab"),
    SLOVES__SMOOTH_STONE_VERTICAL_SLAB("sloves__smooth_stone_vertical_slab"),
    SLOVES__STONE_BRICK_VERTICAL_SLAB("sloves__stone_brick_vertical_slab"),
    SLOVES__SANDSTONE_VERTICAL_SLAB("sloves__sandstone_vertical_slab"),
    SLOVES__PURPUR_VERTICAL_SLAB("sloves__purpur_vertical_slab"),
    SLOVES__QUARTZ_VERTICAL_SLAB("sloves__quartz_vertical_slab"),
    SLOVES__RED_SANDSTONE_VERTICAL_SLAB("sloves__red_sandstone_vertical_slab"),
    SLOVES__BRICK_VERTICAL_SLAB("sloves__brick_vertical_slab"),
    SLOVES__COBBLESTONE_VERTICAL_SLAB("sloves__cobblestone_vertical_slab"),
    SLOVES__NETHER_BRICK_VERTICAL_SLAB("sloves__nether_brick_vertical_slab"),
    SLOVES__PETRIFIED_OAK_VERTICAL_SLAB("sloves__petrified_oak_vertical_slab"),
    SLOVES__PRISMARINE_VERTICAL_SLAB("sloves__prismarine_vertical_slab"),
    SLOVES__PRISMARINE_BRICK_VERTICAL_SLAB("sloves__prismarine_brick_vertical_slab"),
    SLOVES__DARK_PRISMARINE_VERTICAL_SLAB("sloves__dark_prismarine_vertical_slab"),
    SLOVES__POLISHED_GRANITE_VERTICAL_SLAB("sloves__polished_granite_vertical_slab"),
    SLOVES__SMOOTH_RED_SANDSTONE_VERTICAL_SLAB("sloves__smooth_red_sandstone_vertical_slab"),
    SLOVES__MOSSY_STONE_BRICK_VERTICAL_SLAB("sloves__mossy_stone_brick_vertical_slab"),
    SLOVES__POLISHED_DIORITE_VERTICAL_SLAB("sloves__polished_diorite_vertical_slab"),
    SLOVES__MOSSY_COBBLESTONE_VERTICAL_SLAB("sloves__mossy_cobblestone_vertical_slab"),
    SLOVES__END_STONE_BRICK_VERTICAL_SLAB("sloves__end_stone_brick_vertical_slab"),
    SLOVES__SMOOTH_SANDSTONE_VERTICAL_SLAB("sloves__smooth_sandstone_vertical_slab"),
    SLOVES__SMOOTH_QUARTZ_VERTICAL_SLAB("sloves__smooth_quartz_vertical_slab"),
    SLOVES__GRANITE_VERTICAL_SLAB("sloves__granite_vertical_slab"),
    SLOVES__ANDESITE_VERTICAL_SLAB("sloves__andesite_vertical_slab"),
    SLOVES__RED_NETHER_BRICK_VERTICAL_SLAB("sloves__red_nether_brick_vertical_slab"),
    SLOVES__POLISHED_ANDESITE_VERTICAL_SLAB("sloves__polished_andesite_vertical_slab"),
    SLOVES__DIORITE_VERTICAL_SLAB("sloves__diorite_vertical_slab"),
    SLOVES__CUT_SANDSTONE_VERTICAL_SLAB("sloves__cut_sandstone_vertical_slab"),
    SLOVES__CUT_RED_SANDSTONE_VERTICAL_SLAB("sloves__cut_red_sandstone_vertical_slab"),
    SLOVES__BLACKSTONE_VERTICAL_SLAB("sloves__blackstone_vertical_slab"),
    SLOVES__POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB("sloves__polished_blackstone_brick_vertical_slab"),
    SLOVES__POLISHED_BLACKSTONE_VERTICAL_SLAB("sloves__polished_blackstone_vertical_slab"),
    SLOVES__COBBLED_DEEPSLATE_VERTICAL_SLAB("sloves__cobbled_deepslate_vertical_slab"),
    SLOVES__POLISHED_DEEPSLATE_VERTICAL_SLAB("sloves__polished_deepslate_vertical_slab"),
    SLOVES__DEEPSLATE_TILE_VERTICAL_SLAB("sloves__deepslate_tile_vertical_slab"),
    SLOVES__DEEPSLATE_BRICK_VERTICAL_SLAB("sloves__deepslate_brick_vertical_slab"),
    SLOVES__WAXED_WEATHERED_CUT_COPPER_VERTICAL_SLAB("sloves__waxed_weathered_cut_copper_vertical_slab"),
    SLOVES__WAXED_EXPOSED_CUT_COPPER_VERTICAL_SLAB("sloves__waxed_exposed_cut_copper_vertical_slab"),
    SLOVES__WAXED_CUT_COPPER_VERTICAL_SLAB("sloves__waxed_cut_copper_vertical_slab"),
    SLOVES__OXIDIZED_CUT_COPPER_VERTICAL_SLAB("sloves__oxidized_cut_copper_vertical_slab"),
    SLOVES__WEATHERED_CUT_COPPER_VERTICAL_SLAB("sloves__weathered_cut_copper_vertical_slab"),
    SLOVES__EXPOSED_CUT_COPPER_VERTICAL_SLAB("sloves__exposed_cut_copper_vertical_slab"),
    SLOVES__CUT_COPPER_VERTICAL_SLAB("sloves__cut_copper_vertical_slab"),
    SLOVES__WAXED_OXIDIZED_CUT_COPPER_VERTICAL_SLAB("sloves__waxed_oxidized_cut_copper_vertical_slab"),
    SLOVES__MUD_BRICK_VERTICAL_SLAB("sloves__mud_brick_vertical_slab"),
    SLOVES__TUFF_VERTICAL_SLAB("sloves__tuff_vertical_slab"),
    SLOVES__POLISHED_TUFF_VERTICAL_SLAB("sloves__polished_tuff_vertical_slab"),
    SLOVES__TUFF_BRICK_VERTICAL_SLAB("sloves__tuff_brick_vertical_slab"),
    SLOVES__CRACKED_STONE_BRICK_VERTICAL_SLAB("sloves__cracked_stone_brick_vertical_slab"),
    SLOVES__DEEPSLATE_VERTICAL_SLAB("sloves__deepslate_vertical_slab"),
    SLOVES__CRACKED_DEEPSLATE_BRICK_VERTICAL_SLAB("sloves__cracked_deepslate_brick_vertical_slab"),
    SLOVES__REINFORCED_DEEPSLATE_VERTICAL_SLAB("sloves__reinforced_deepslate_vertical_slab"),
    SLOVES__PACKED_MUD_VERTICAL_SLAB("sloves__packed_mud_vertical_slab"),
    SLOVES__NETHERRACK_VERTICAL_SLAB("sloves__netherrack_vertical_slab"),
    SLOVES__CRACKED_NETHER_BRICK_VERTICAL_SLAB("sloves__cracked_nether_brick_vertical_slab"),
    SLOVES__BASALT_VERTICAL_SLAB("sloves__basalt_vertical_slab"),
    SLOVES__SMOOTH_BASALT_VERTICAL_SLAB("sloves__smooth_basalt_vertical_slab"),
    SLOVES__POLISHED_BASALT_VERTICAL_SLAB("sloves__polished_basalt_vertical_slab"),
    SLOVES__GILDED_BLACKSTONE_VERTICAL_SLAB("sloves__gilded_blackstone_vertical_slab"),
    SLOVES__CRACKED_POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB("sloves__cracked_polished_blackstone_brick_vertical_slab"),
    SLOVES__END_STONE_VERTICAL_SLAB("sloves__end_stone_vertical_slab"),
    SLOVES__PURPUR_PILLAR_VERTICAL_SLAB("sloves__purpur_pillar_vertical_slab"),
    SLOVES__QUARTZ_BRICK_VERTICAL_SLAB("sloves__quartz_brick_vertical_slab"),
    SLOVES__QUARTZ_PILLAR_VERTICAL_SLAB("sloves__quartz_pillar_vertical_slab"),
    SLOVES__AMETHYST_VERTICAL_SLAB("sloves__amethyst_vertical_slab"),
    SLOVES__WHITE_WOOL_VERTICAL_SLAB("sloves__white_wool_vertical_slab"),
    SLOVES__LIGHT_GRAY_WOOL_VERTICAL_SLAB("sloves__light_gray_wool_vertical_slab"),
    SLOVES__GRAY_WOOL_VERTICAL_SLAB("sloves__gray_wool_vertical_slab"),
    SLOVES__BLACK_WOOL_VERTICAL_SLAB("sloves__black_wool_vertical_slab"),
    SLOVES__BROWN_WOOL_VERTICAL_SLAB("sloves__brown_wool_vertical_slab"),
    SLOVES__RED_WOOL_VERTICAL_SLAB("sloves__red_wool_vertical_slab"),
    SLOVES__ORANGE_WOOL_VERTICAL_SLAB("sloves__orange_wool_vertical_slab"),
    SLOVES__YELLOW_WOOL_VERTICAL_SLAB("sloves__yellow_wool_vertical_slab"),
    SLOVES__LIME_WOOL_VERTICAL_SLAB("sloves__lime_wool_vertical_slab"),
    SLOVES__GREEN_WOOL_VERTICAL_SLAB("sloves__green_wool_vertical_slab"),
    SLOVES__CYAN_WOOL_VERTICAL_SLAB("sloves__cyan_wool_vertical_slab"),
    SLOVES__LIGHT_BLUE_WOOL_VERTICAL_SLAB("sloves__light_blue_wool_vertical_slab"),
    SLOVES__BLUE_WOOL_VERTICAL_SLAB("sloves__blue_wool_vertical_slab"),
    SLOVES__PURPLE_WOOL_VERTICAL_SLAB("sloves__purple_wool_vertical_slab"),
    SLOVES__MAGENTA_WOOL_VERTICAL_SLAB("sloves__magenta_wool_vertical_slab"),
    SLOVES__PINK_WOOL_VERTICAL_SLAB("sloves__pink_wool_vertical_slab"),
    SLOVES__TERRACOTTA_VERTICAL_SLAB("sloves__terracotta_vertical_slab"),
    SLOVES__WHITE_TERRACOTTA_VERTICAL_SLAB("sloves__white_terracotta_vertical_slab"),
    SLOVES__LIGHT_GRAY_TERRACOTTA_VERTICAL_SLAB("sloves__light_gray_terracotta_vertical_slab"),
    SLOVES__GRAY_TERRACOTTA_VERTICAL_SLAB("sloves__gray_terracotta_vertical_slab"),
    SLOVES__BLACK_TERRACOTTA_VERTICAL_SLAB("sloves__black_terracotta_vertical_slab"),
    SLOVES__BROWN_TERRACOTTA_VERTICAL_SLAB("sloves__brown_terracotta_vertical_slab"),
    SLOVES__RED_TERRACOTTA_VERTICAL_SLAB("sloves__red_terracotta_vertical_slab"),
    SLOVES__ORANGE_TERRACOTTA_VERTICAL_SLAB("sloves__orange_terracotta_vertical_slab"),
    SLOVES__YELLOW_TERRACOTTA_VERTICAL_SLAB("sloves__yellow_terracotta_vertical_slab"),
    SLOVES__LIME_TERRACOTTA_VERTICAL_SLAB("sloves__lime_terracotta_vertical_slab"),
    SLOVES__GREEN_TERRACOTTA_VERTICAL_SLAB("sloves__green_terracotta_vertical_slab"),
    SLOVES__CYAN_TERRACOTTA_VERTICAL_SLAB("sloves__cyan_terracotta_vertical_slab"),
    SLOVES__LIGHT_BLUE_TERRACOTTA_VERTICAL_SLAB("sloves__light_blue_terracotta_vertical_slab"),
    SLOVES__BLUE_TERRACOTTA_VERTICAL_SLAB("sloves__blue_terracotta_vertical_slab"),
    SLOVES__PURPLE_TERRACOTTA_VERTICAL_SLAB("sloves__purple_terracotta_vertical_slab"),
    SLOVES__MAGENTA_TERRACOTTA_VERTICAL_SLAB("sloves__magenta_terracotta_vertical_slab"),
    SLOVES__PINK_TERRACOTTA_VERTICAL_SLAB("sloves__pink_terracotta_vertical_slab"),
    SLOVES__WHITE_CONCRETE_VERTICAL_SLAB("sloves__white_concrete_vertical_slab"),
    SLOVES__LIGHT_GRAY_CONCRETE_VERTICAL_SLAB("sloves__light_gray_concrete_vertical_slab"),
    SLOVES__GRAY_CONCRETE_VERTICAL_SLAB("sloves__gray_concrete_vertical_slab"),
    SLOVES__BLACK_CONCRETE_VERTICAL_SLAB("sloves__black_concrete_vertical_slab"),
    SLOVES__BROWN_CONCRETE_VERTICAL_SLAB("sloves__brown_concrete_vertical_slab"),
    SLOVES__RED_CONCRETE_VERTICAL_SLAB("sloves__red_concrete_vertical_slab"),
    SLOVES__ORANGE_CONCRETE_VERTICAL_SLAB("sloves__orange_concrete_vertical_slab"),
    SLOVES__YELLOW_CONCRETE_VERTICAL_SLAB("sloves__yellow_concrete_vertical_slab"),
    SLOVES__LIME_CONCRETE_VERTICAL_SLAB("sloves__lime_concrete_vertical_slab"),
    SLOVES__GREEN_CONCRETE_VERTICAL_SLAB("sloves__green_concrete_vertical_slab"),
    SLOVES__CYAN_CONCRETE_VERTICAL_SLAB("sloves__cyan_concrete_vertical_slab"),
    SLOVES__LIGHT_BLUE_CONCRETE_VERTICAL_SLAB("sloves__light_blue_concrete_vertical_slab"),
    SLOVES__BLUE_CONCRETE_VERTICAL_SLAB("sloves__blue_concrete_vertical_slab"),
    SLOVES__PURPLE_CONCRETE_VERTICAL_SLAB("sloves__purple_concrete_vertical_slab"),
    SLOVES__MAGENTA_CONCRETE_VERTICAL_SLAB("sloves__magenta_concrete_vertical_slab"),
    SLOVES__PINK_CONCRETE_VERTICAL_SLAB("sloves__pink_concrete_vertical_slab"),
    SLOVES__WHITE_CONCRETE_POWDER_VERTICAL_SLAB("sloves__white_concrete_powder_vertical_slab"),
    SLOVES__LIGHT_GRAY_CONCRETE_POWDER_VERTICAL_SLAB("sloves__light_gray_concrete_powder_vertical_slab"),
    SLOVES__GRAY_CONCRETE_POWDER_VERTICAL_SLAB("sloves__gray_concrete_powder_vertical_slab"),
    SLOVES__BLACK_CONCRETE_POWDER_VERTICAL_SLAB("sloves__black_concrete_powder_vertical_slab"),
    SLOVES__BROWN_CONCRETE_POWDER_VERTICAL_SLAB("sloves__brown_concrete_powder_vertical_slab"),
    SLOVES__RED_CONCRETE_POWDER_VERTICAL_SLAB("sloves__red_concrete_powder_vertical_slab"),
    SLOVES__ORANGE_CONCRETE_POWDER_VERTICAL_SLAB("sloves__orange_concrete_powder_vertical_slab"),
    SLOVES__YELLOW_CONCRETE_POWDER_VERTICAL_SLAB("sloves__yellow_concrete_powder_vertical_slab"),
    SLOVES__LIME_CONCRETE_POWDER_VERTICAL_SLAB("sloves__lime_concrete_powder_vertical_slab"),
    SLOVES__GREEN_CONCRETE_POWDER_VERTICAL_SLAB("sloves__green_concrete_powder_vertical_slab"),
    SLOVES__CYAN_CONCRETE_POWDER_VERTICAL_SLAB("sloves__cyan_concrete_powder_vertical_slab"),
    SLOVES__LIGHT_BLUE_CONCRETE_POWDER_VERTICAL_SLAB("sloves__light_blue_concrete_powder_vertical_slab"),
    SLOVES__BLUE_CONCRETE_POWDER_VERTICAL_SLAB("sloves__blue_concrete_powder_vertical_slab"),
    SLOVES__PURPLE_CONCRETE_POWDER_VERTICAL_SLAB("sloves__purple_concrete_powder_vertical_slab"),
    SLOVES__MAGENTA_CONCRETE_POWDER_VERTICAL_SLAB("sloves__magenta_concrete_powder_vertical_slab"),
    SLOVES__PINK_CONCRETE_POWDER_VERTICAL_SLAB("sloves__pink_concrete_powder_vertical_slab");
    /* END MARKER */

    private final String name;

    CustomVerticalSlabType(String name) {
        this.name = name;
    }

    @Override
    public String asString() {
        return this.name;
    }

    public static CustomVerticalSlabType fromString(String name) {
        name = name.replace(":","__");
        for (CustomVerticalSlabType value : CustomVerticalSlabType.values()) {
            if (value.asString().equals(name)) {
                return value;
            }
        }
        return NONE;
    }
}
