package com.forestotzka.yurufu.sloves.block.enums;

import net.minecraft.util.StringIdentifiable;

public enum CustomSlabType implements StringIdentifiable {

    /* START MARKER */
    NONE("minecraft__air"),
    MINECRAFT__OAK_SLAB("minecraft__oak_slab"),
    MINECRAFT__SPRUCE_SLAB("minecraft__spruce_slab"),
    MINECRAFT__BIRCH_SLAB("minecraft__birch_slab"),
    MINECRAFT__JUNGLE_SLAB("minecraft__jungle_slab"),
    MINECRAFT__ACACIA_SLAB("minecraft__acacia_slab"),
    MINECRAFT__DARK_OAK_SLAB("minecraft__dark_oak_slab"),
    MINECRAFT__CRIMSON_SLAB("minecraft__crimson_slab"),
    MINECRAFT__WARPED_SLAB("minecraft__warped_slab"),
    MINECRAFT__MANGROVE_SLAB("minecraft__mangrove_slab"),
    MINECRAFT__BAMBOO_SLAB("minecraft__bamboo_slab"),
    MINECRAFT__CHERRY_SLAB("minecraft__cherry_slab"),
    MINECRAFT__BAMBOO_MOSAIC_SLAB("minecraft__bamboo_mosaic_slab"),
    MINECRAFT__STONE_SLAB("minecraft__stone_slab"),
    MINECRAFT__SMOOTH_STONE_SLAB("minecraft__smooth_stone_slab"),
    MINECRAFT__STONE_BRICK_SLAB("minecraft__stone_brick_slab"),
    MINECRAFT__SANDSTONE_SLAB("minecraft__sandstone_slab"),
    MINECRAFT__PURPUR_SLAB("minecraft__purpur_slab"),
    MINECRAFT__QUARTZ_SLAB("minecraft__quartz_slab"),
    MINECRAFT__RED_SANDSTONE_SLAB("minecraft__red_sandstone_slab"),
    MINECRAFT__BRICK_SLAB("minecraft__brick_slab"),
    MINECRAFT__COBBLESTONE_SLAB("minecraft__cobblestone_slab"),
    MINECRAFT__NETHER_BRICK_SLAB("minecraft__nether_brick_slab"),
    MINECRAFT__PETRIFIED_OAK_SLAB("minecraft__petrified_oak_slab"),
    MINECRAFT__PRISMARINE_SLAB("minecraft__prismarine_slab"),
    MINECRAFT__PRISMARINE_BRICK_SLAB("minecraft__prismarine_brick_slab"),
    MINECRAFT__DARK_PRISMARINE_SLAB("minecraft__dark_prismarine_slab"),
    MINECRAFT__POLISHED_GRANITE_SLAB("minecraft__polished_granite_slab"),
    MINECRAFT__SMOOTH_RED_SANDSTONE_SLAB("minecraft__smooth_red_sandstone_slab"),
    MINECRAFT__MOSSY_STONE_BRICK_SLAB("minecraft__mossy_stone_brick_slab"),
    MINECRAFT__POLISHED_DIORITE_SLAB("minecraft__polished_diorite_slab"),
    MINECRAFT__MOSSY_COBBLESTONE_SLAB("minecraft__mossy_cobblestone_slab"),
    MINECRAFT__END_STONE_BRICK_SLAB("minecraft__end_stone_brick_slab"),
    MINECRAFT__SMOOTH_SANDSTONE_SLAB("minecraft__smooth_sandstone_slab"),
    MINECRAFT__SMOOTH_QUARTZ_SLAB("minecraft__smooth_quartz_slab"),
    MINECRAFT__GRANITE_SLAB("minecraft__granite_slab"),
    MINECRAFT__ANDESITE_SLAB("minecraft__andesite_slab"),
    MINECRAFT__RED_NETHER_BRICK_SLAB("minecraft__red_nether_brick_slab"),
    MINECRAFT__POLISHED_ANDESITE_SLAB("minecraft__polished_andesite_slab"),
    MINECRAFT__DIORITE_SLAB("minecraft__diorite_slab"),
    MINECRAFT__CUT_SANDSTONE_SLAB("minecraft__cut_sandstone_slab"),
    MINECRAFT__CUT_RED_SANDSTONE_SLAB("minecraft__cut_red_sandstone_slab"),
    MINECRAFT__BLACKSTONE_SLAB("minecraft__blackstone_slab"),
    MINECRAFT__POLISHED_BLACKSTONE_BRICK_SLAB("minecraft__polished_blackstone_brick_slab"),
    MINECRAFT__POLISHED_BLACKSTONE_SLAB("minecraft__polished_blackstone_slab"),
    MINECRAFT__COBBLED_DEEPSLATE_SLAB("minecraft__cobbled_deepslate_slab"),
    MINECRAFT__POLISHED_DEEPSLATE_SLAB("minecraft__polished_deepslate_slab"),
    MINECRAFT__DEEPSLATE_TILE_SLAB("minecraft__deepslate_tile_slab"),
    MINECRAFT__DEEPSLATE_BRICK_SLAB("minecraft__deepslate_brick_slab"),
    MINECRAFT__WAXED_WEATHERED_CUT_COPPER_SLAB("minecraft__waxed_weathered_cut_copper_slab"),
    MINECRAFT__WAXED_EXPOSED_CUT_COPPER_SLAB("minecraft__waxed_exposed_cut_copper_slab"),
    MINECRAFT__WAXED_CUT_COPPER_SLAB("minecraft__waxed_cut_copper_slab"),
    MINECRAFT__OXIDIZED_CUT_COPPER_SLAB("minecraft__oxidized_cut_copper_slab"),
    MINECRAFT__WEATHERED_CUT_COPPER_SLAB("minecraft__weathered_cut_copper_slab"),
    MINECRAFT__EXPOSED_CUT_COPPER_SLAB("minecraft__exposed_cut_copper_slab"),
    MINECRAFT__CUT_COPPER_SLAB("minecraft__cut_copper_slab"),
    MINECRAFT__WAXED_OXIDIZED_CUT_COPPER_SLAB("minecraft__waxed_oxidized_cut_copper_slab"),
    MINECRAFT__MUD_BRICK_SLAB("minecraft__mud_brick_slab"),
    MINECRAFT__TUFF_SLAB("minecraft__tuff_slab"),
    MINECRAFT__POLISHED_TUFF_SLAB("minecraft__polished_tuff_slab"),
    MINECRAFT__TUFF_BRICK_SLAB("minecraft__tuff_brick_slab"),
    SLOVES__OAK_LOG_SLAB("sloves__oak_log_slab"),
    SLOVES__SPRUCE_LOG_SLAB("sloves__spruce_log_slab"),
    SLOVES__BIRCH_LOG_SLAB("sloves__birch_log_slab"),
    SLOVES__JUNGLE_LOG_SLAB("sloves__jungle_log_slab"),
    SLOVES__ACACIA_LOG_SLAB("sloves__acacia_log_slab"),
    SLOVES__DARK_OAK_LOG_SLAB("sloves__dark_oak_log_slab"),
    SLOVES__MANGROVE_LOG_SLAB("sloves__mangrove_log_slab"),
    SLOVES__CHERRY_LOG_SLAB("sloves__cherry_log_slab"),
    SLOVES__BAMBOO_SLAB("sloves__bamboo_slab"),
    SLOVES__CRIMSON_STEM_SLAB("sloves__crimson_stem_slab"),
    SLOVES__WARPED_STEM_SLAB("sloves__warped_stem_slab"),
    SLOVES__OAK_WOOD_SLAB("sloves__oak_wood_slab"),
    SLOVES__SPRUCE_WOOD_SLAB("sloves__spruce_wood_slab"),
    SLOVES__BIRCH_WOOD_SLAB("sloves__birch_wood_slab"),
    SLOVES__JUNGLE_WOOD_SLAB("sloves__jungle_wood_slab"),
    SLOVES__ACACIA_WOOD_SLAB("sloves__acacia_wood_slab"),
    SLOVES__DARK_OAK_WOOD_SLAB("sloves__dark_oak_wood_slab"),
    SLOVES__MANGROVE_WOOD_SLAB("sloves__mangrove_wood_slab"),
    SLOVES__CHERRY_WOOD_SLAB("sloves__cherry_wood_slab"),
    SLOVES__CRIMSON_HYPHAE_SLAB("sloves__crimson_hyphae_slab"),
    SLOVES__WARPED_HYPHAE_SLAB("sloves__warped_hyphae_slab"),
    SLOVES__STRIPPED_OAK_LOG_SLAB("sloves__stripped_oak_log_slab"),
    SLOVES__STRIPPED_SPRUCE_LOG_SLAB("sloves__stripped_spruce_log_slab"),
    SLOVES__STRIPPED_BIRCH_LOG_SLAB("sloves__stripped_birch_log_slab"),
    SLOVES__STRIPPED_JUNGLE_LOG_SLAB("sloves__stripped_jungle_log_slab"),
    SLOVES__STRIPPED_ACACIA_LOG_SLAB("sloves__stripped_acacia_log_slab"),
    SLOVES__STRIPPED_DARK_OAK_LOG_SLAB("sloves__stripped_dark_oak_log_slab"),
    SLOVES__STRIPPED_MANGROVE_LOG_SLAB("sloves__stripped_mangrove_log_slab"),
    SLOVES__STRIPPED_CHERRY_LOG_SLAB("sloves__stripped_cherry_log_slab"),
    SLOVES__STRIPPED_BAMBOO_SLAB("sloves__stripped_bamboo_slab"),
    SLOVES__STRIPPED_CRIMSON_STEM_SLAB("sloves__stripped_crimson_stem_slab"),
    SLOVES__STRIPPED_WARPED_STEM_SLAB("sloves__stripped_warped_stem_slab"),
    SLOVES__STRIPPED_OAK_WOOD_SLAB("sloves__stripped_oak_wood_slab"),
    SLOVES__STRIPPED_SPRUCE_WOOD_SLAB("sloves__stripped_spruce_wood_slab"),
    SLOVES__STRIPPED_BIRCH_WOOD_SLAB("sloves__stripped_birch_wood_slab"),
    SLOVES__STRIPPED_JUNGLE_WOOD_SLAB("sloves__stripped_jungle_wood_slab"),
    SLOVES__STRIPPED_ACACIA_WOOD_SLAB("sloves__stripped_acacia_wood_slab"),
    SLOVES__STRIPPED_DARK_OAK_WOOD_SLAB("sloves__stripped_dark_oak_wood_slab"),
    SLOVES__STRIPPED_MANGROVE_WOOD_SLAB("sloves__stripped_mangrove_wood_slab"),
    SLOVES__STRIPPED_CHERRY_WOOD_SLAB("sloves__stripped_cherry_wood_slab"),
    SLOVES__STRIPPED_CRIMSON_HYPHAE_SLAB("sloves__stripped_crimson_hyphae_slab"),
    SLOVES__STRIPPED_WARPED_HYPHAE_SLAB("sloves__stripped_warped_hyphae_slab"),
    SLOVES__CRACKED_STONE_BRICK_SLAB("sloves__cracked_stone_brick_slab"),
    SLOVES__DEEPSLATE_SLAB("sloves__deepslate_slab"),
    SLOVES__CRACKED_DEEPSLATE_BRICK_SLAB("sloves__cracked_deepslate_brick_slab"),
    SLOVES__REINFORCED_DEEPSLATE_SLAB("sloves__reinforced_deepslate_slab"),
    SLOVES__PACKED_MUD_SLAB("sloves__packed_mud_slab"),
    SLOVES__NETHERRACK_SLAB("sloves__netherrack_slab"),
    SLOVES__CRACKED_NETHER_BRICK_SLAB("sloves__cracked_nether_brick_slab"),
    SLOVES__BASALT_SLAB("sloves__basalt_slab"),
    SLOVES__SMOOTH_BASALT_SLAB("sloves__smooth_basalt_slab"),
    SLOVES__POLISHED_BASALT_SLAB("sloves__polished_basalt_slab"),
    SLOVES__GILDED_BLACKSTONE_SLAB("sloves__gilded_blackstone_slab"),
    SLOVES__CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB("sloves__cracked_polished_blackstone_brick_slab"),
    SLOVES__END_STONE_SLAB("sloves__end_stone_slab"),
    SLOVES__PURPUR_PILLAR_SLAB("sloves__purpur_pillar_slab"),
    SLOVES__QUARTZ_BRICK_SLAB("sloves__quartz_brick_slab"),
    SLOVES__QUARTZ_PILLAR_SLAB("sloves__quartz_pillar_slab"),
    SLOVES__AMETHYST_SLAB("sloves__amethyst_slab"),
    SLOVES__WHITE_WOOL_SLAB("sloves__white_wool_slab"),
    SLOVES__LIGHT_GRAY_WOOL_SLAB("sloves__light_gray_wool_slab"),
    SLOVES__GRAY_WOOL_SLAB("sloves__gray_wool_slab"),
    SLOVES__BLACK_WOOL_SLAB("sloves__black_wool_slab"),
    SLOVES__BROWN_WOOL_SLAB("sloves__brown_wool_slab"),
    SLOVES__RED_WOOL_SLAB("sloves__red_wool_slab"),
    SLOVES__ORANGE_WOOL_SLAB("sloves__orange_wool_slab"),
    SLOVES__YELLOW_WOOL_SLAB("sloves__yellow_wool_slab"),
    SLOVES__LIME_WOOL_SLAB("sloves__lime_wool_slab"),
    SLOVES__GREEN_WOOL_SLAB("sloves__green_wool_slab"),
    SLOVES__CYAN_WOOL_SLAB("sloves__cyan_wool_slab"),
    SLOVES__LIGHT_BLUE_WOOL_SLAB("sloves__light_blue_wool_slab"),
    SLOVES__BLUE_WOOL_SLAB("sloves__blue_wool_slab"),
    SLOVES__PURPLE_WOOL_SLAB("sloves__purple_wool_slab"),
    SLOVES__MAGENTA_WOOL_SLAB("sloves__magenta_wool_slab"),
    SLOVES__PINK_WOOL_SLAB("sloves__pink_wool_slab"),
    SLOVES__TERRACOTTA_SLAB("sloves__terracotta_slab"),
    SLOVES__WHITE_TERRACOTTA_SLAB("sloves__white_terracotta_slab"),
    SLOVES__LIGHT_GRAY_TERRACOTTA_SLAB("sloves__light_gray_terracotta_slab"),
    SLOVES__GRAY_TERRACOTTA_SLAB("sloves__gray_terracotta_slab"),
    SLOVES__BLACK_TERRACOTTA_SLAB("sloves__black_terracotta_slab"),
    SLOVES__BROWN_TERRACOTTA_SLAB("sloves__brown_terracotta_slab"),
    SLOVES__RED_TERRACOTTA_SLAB("sloves__red_terracotta_slab"),
    SLOVES__ORANGE_TERRACOTTA_SLAB("sloves__orange_terracotta_slab"),
    SLOVES__YELLOW_TERRACOTTA_SLAB("sloves__yellow_terracotta_slab"),
    SLOVES__LIME_TERRACOTTA_SLAB("sloves__lime_terracotta_slab"),
    SLOVES__GREEN_TERRACOTTA_SLAB("sloves__green_terracotta_slab"),
    SLOVES__CYAN_TERRACOTTA_SLAB("sloves__cyan_terracotta_slab"),
    SLOVES__LIGHT_BLUE_TERRACOTTA_SLAB("sloves__light_blue_terracotta_slab"),
    SLOVES__BLUE_TERRACOTTA_SLAB("sloves__blue_terracotta_slab"),
    SLOVES__PURPLE_TERRACOTTA_SLAB("sloves__purple_terracotta_slab"),
    SLOVES__MAGENTA_TERRACOTTA_SLAB("sloves__magenta_terracotta_slab"),
    SLOVES__PINK_TERRACOTTA_SLAB("sloves__pink_terracotta_slab"),
    SLOVES__WHITE_CONCRETE_SLAB("sloves__white_concrete_slab"),
    SLOVES__LIGHT_GRAY_CONCRETE_SLAB("sloves__light_gray_concrete_slab"),
    SLOVES__GRAY_CONCRETE_SLAB("sloves__gray_concrete_slab"),
    SLOVES__BLACK_CONCRETE_SLAB("sloves__black_concrete_slab"),
    SLOVES__BROWN_CONCRETE_SLAB("sloves__brown_concrete_slab"),
    SLOVES__RED_CONCRETE_SLAB("sloves__red_concrete_slab"),
    SLOVES__ORANGE_CONCRETE_SLAB("sloves__orange_concrete_slab"),
    SLOVES__YELLOW_CONCRETE_SLAB("sloves__yellow_concrete_slab"),
    SLOVES__LIME_CONCRETE_SLAB("sloves__lime_concrete_slab"),
    SLOVES__GREEN_CONCRETE_SLAB("sloves__green_concrete_slab"),
    SLOVES__CYAN_CONCRETE_SLAB("sloves__cyan_concrete_slab"),
    SLOVES__LIGHT_BLUE_CONCRETE_SLAB("sloves__light_blue_concrete_slab"),
    SLOVES__BLUE_CONCRETE_SLAB("sloves__blue_concrete_slab"),
    SLOVES__PURPLE_CONCRETE_SLAB("sloves__purple_concrete_slab"),
    SLOVES__MAGENTA_CONCRETE_SLAB("sloves__magenta_concrete_slab"),
    SLOVES__PINK_CONCRETE_SLAB("sloves__pink_concrete_slab"),
    SLOVES__WHITE_CONCRETE_POWDER_SLAB("sloves__white_concrete_powder_slab"),
    SLOVES__LIGHT_GRAY_CONCRETE_POWDER_SLAB("sloves__light_gray_concrete_powder_slab"),
    SLOVES__GRAY_CONCRETE_POWDER_SLAB("sloves__gray_concrete_powder_slab"),
    SLOVES__BLACK_CONCRETE_POWDER_SLAB("sloves__black_concrete_powder_slab"),
    SLOVES__BROWN_CONCRETE_POWDER_SLAB("sloves__brown_concrete_powder_slab"),
    SLOVES__RED_CONCRETE_POWDER_SLAB("sloves__red_concrete_powder_slab"),
    SLOVES__ORANGE_CONCRETE_POWDER_SLAB("sloves__orange_concrete_powder_slab"),
    SLOVES__YELLOW_CONCRETE_POWDER_SLAB("sloves__yellow_concrete_powder_slab"),
    SLOVES__LIME_CONCRETE_POWDER_SLAB("sloves__lime_concrete_powder_slab"),
    SLOVES__GREEN_CONCRETE_POWDER_SLAB("sloves__green_concrete_powder_slab"),
    SLOVES__CYAN_CONCRETE_POWDER_SLAB("sloves__cyan_concrete_powder_slab"),
    SLOVES__LIGHT_BLUE_CONCRETE_POWDER_SLAB("sloves__light_blue_concrete_powder_slab"),
    SLOVES__BLUE_CONCRETE_POWDER_SLAB("sloves__blue_concrete_powder_slab"),
    SLOVES__PURPLE_CONCRETE_POWDER_SLAB("sloves__purple_concrete_powder_slab"),
    SLOVES__MAGENTA_CONCRETE_POWDER_SLAB("sloves__magenta_concrete_powder_slab"),
    SLOVES__PINK_CONCRETE_POWDER_SLAB("sloves__pink_concrete_powder_slab"),
    SLOVES__GRASS_SLAB("sloves__grass_slab"),
    SLOVES__DIRT_SLAB("sloves__dirt_slab");
    /* END MARKER */

    private final String name;

    CustomSlabType(String name) {
        this.name = name;
    }

    @Override
    public String asString() {
        return this.name;
    }

    public static CustomSlabType fromString(String name) {
        name = name.replace(":","__");
        for (CustomSlabType value : CustomSlabType.values()) {
            if (value.asString().equals(name)) {
                return value;
            }
        }
        return NONE;
    }
}
